name: Test Coverage

on: [pull_request]

jobs:
  coverage:

    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
      
      - name: Test Coverage
        run: make coverage
        
      - name: Setup LCOV
        uses: hrishikesh-kadam/setup-lcov@d100c36c45e4f64950fb746cd28713f6c756a9c1
      - name: Report code coverage
        uses: zgosalvez/github-actions-report-lcov@5f5c6e77851c41ab9c69a212690c1040bb916016
        with:
          coverage-files: coverage/lcov.info
          minimum-coverage: 40
          github-token: ${{ secrets.GITHUB_TOKEN }}
          update-comment: true
