name: Go build & test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.5

      - name: Build
        run: make build

      - name: Test
        run: make test
      
      - name: Test Coverage
        run: make coverage
        
      - name: Setup LCOV
        uses: hrishikesh-kadam/setup-lcov@v1
      - name: Report code coverage
        uses: zgosalvez/github-actions-report-lcov@v3
        with:
          coverage-files: coverage/lcov.info
          minimum-coverage: 50
          github-token: ${{ secrets.GITHUB_TOKEN }}
          working-directory: apps/my-first-app
          update-comment: true